# Generated by Django 5.0.1 on 2024-02-18 12:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_uploadedfile_delete_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockFuturesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SYMBOL', models.CharField(default=None, max_length=120)),
                ('OPEN', models.FloatField(default=0.0)),
                ('HIGH', models.FloatField(default=0.0)),
                ('LOW', models.FloatField(default=0.0)),
                ('CLOSE', models.FloatField(default=0.0)),
                ('VOLUME', models.FloatField(default=0.0)),
                ('OPEN_INT', models.FloatField(default=None, max_length=120)),
                ('CHG_IN_OI', models.FloatField(default=0.0)),
                ('TIMESTAMP', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
